[tool.poetry]
name = "fast-djanga"
version = "0.0.1"
description = "FastAPI project constructor"
authors = ["Dooby Douglas"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
